/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as RequesterRouteImport } from './routes/requester'
import { Route as AuthenticatedDeskRouteImport } from './routes/_authenticated/desk'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated/intake'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedIntroductionsIdRouteImport } from './routes/_authenticated/introductions.$id'
import { Route as ApiPublicRunMatchingRouteImport } from './routes/api/public/run-matching'
import { Route as ApiPublicWebhooksAmbiguousRouteImport } from './routes/api/public/webhooks/ambiguous'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const RequesterRoute = RequesterRouteImport.update({
  id: '/requester',
  path: '/requester',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeskRoute = AuthenticatedDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntroductionsIdRoute =
  AuthenticatedIntroductionsIdRouteImport.update({
    id: '/introductions/$id',
    path: '/introductions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicRunMatchingRoute = ApiPublicRunMatchingRouteImport.update({
  id: '/api/public/run-matching',
  path: '/api/public/run-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksAmbiguousRoute =
  ApiPublicWebhooksAmbiguousRouteImport.update({
    id: '/api/public/webhooks/ambiguous',
    path: '/api/public/webhooks/ambiguous',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/provider': typeof ProviderRoute
  '/requester': typeof RequesterRoute
  '/desk': typeof AuthenticatedDeskRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/introductions/$id': typeof AuthenticatedIntroductionsIdRoute
  '/api/public/run-matching': typeof ApiPublicRunMatchingRoute
  '/api/public/webhooks/ambiguous': typeof ApiPublicWebhooksAmbiguousRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/provider': typeof ProviderRoute
  '/requester': typeof RequesterRoute
  '/desk': typeof AuthenticatedDeskRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/introductions/$id': typeof AuthenticatedIntroductionsIdRoute
  '/api/public/run-matching': typeof ApiPublicRunMatchingRoute
  '/api/public/webhooks/ambiguous': typeof ApiPublicWebhooksAmbiguousRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/provider': typeof ProviderRoute
  '/requester': typeof RequesterRoute
  '/_authenticated/desk': typeof AuthenticatedDeskRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/_authenticated/introductions/$id': typeof AuthenticatedIntroductionsIdRoute
  '/api/public/run-matching': typeof ApiPublicRunMatchingRoute
  '/api/public/webhooks/ambiguous': typeof ApiPublicWebhooksAmbiguousRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/provider'
    | '/requester'
    | '/desk'
    | '/intake'
    | '/operator'
    | '/introductions/$id'
    | '/api/public/run-matching'
    | '/api/public/webhooks/ambiguous'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/provider'
    | '/requester'
    | '/desk'
    | '/intake'
    | '/operator'
    | '/introductions/$id'
    | '/api/public/run-matching'
    | '/api/public/webhooks/ambiguous'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/provider'
    | '/requester'
    | '/_authenticated/desk'
    | '/_authenticated/intake'
    | '/_authenticated/operator'
    | '/_authenticated/introductions/$id'
    | '/api/public/run-matching'
    | '/api/public/webhooks/ambiguous'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProviderRoute: typeof ProviderRoute
  RequesterRoute: typeof RequesterRoute
  ApiPublicRunMatchingRoute: typeof ApiPublicRunMatchingRoute
  ApiPublicWebhooksAmbiguousRoute: typeof ApiPublicWebhooksAmbiguousRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requester': {
      id: '/requester'
      path: '/requester'
      fullPath: '/requester'
      preLoaderRoute: typeof RequesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/desk': {
      id: '/_authenticated/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof AuthenticatedDeskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/introductions/$id': {
      id: '/_authenticated/introductions/$id'
      path: '/introductions/$id'
      fullPath: '/introductions/$id'
      preLoaderRoute: typeof AuthenticatedIntroductionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/run-matching': {
      id: '/api/public/run-matching'
      path: '/api/public/run-matching'
      fullPath: '/api/public/run-matching'
      preLoaderRoute: typeof ApiPublicRunMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/ambiguous': {
      id: '/api/public/webhooks/ambiguous'
      path: '/api/public/webhooks/ambiguous'
      fullPath: '/api/public/webhooks/ambiguous'
      preLoaderRoute: typeof ApiPublicWebhooksAmbiguousRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDeskRoute: typeof AuthenticatedDeskRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
  AuthenticatedIntroductionsIdRoute: typeof AuthenticatedIntroductionsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDeskRoute: AuthenticatedDeskRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
  AuthenticatedIntroductionsIdRoute: AuthenticatedIntroductionsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProviderRoute: ProviderRoute,
  RequesterRoute: RequesterRoute,
  ApiPublicRunMatchingRoute: ApiPublicRunMatchingRoute,
  ApiPublicWebhooksAmbiguousRoute: ApiPublicWebhooksAmbiguousRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
